### PR TITLE
add Indonesian translation

### PR DESCRIPTION
**Pull request by srvsetiawan**
hello I just added translation into Indonesian, so that Indonesian users can interact with the app without language barriers.

### CODE REVIEW

**Comment by neuromorph** [comment]
Hello Ilham,
Thanks a lot for your contribution! However, recently there has been an update to the app with addition of the Profiles tab in the settings. Since there were no translations at the moment, unfortunately, I was running late on updating the .pot file. (Also yet to port the update to Gnome 45).  

I have now updated the .pot file. While most of the original strings remain the same (thus retaining the translation as well), there are new strings from Profiles tab and maybe a few minor changes. I would request you to merge with the new pot file and help with the missing strings' translation so that the whole app can reflect Indonesian. 
[This link ](https://stacktuts.com/how-to-update-po-and-pot-files-after-the-source-is-modified-in-gettext) provides steps to merge updated pot file into your po. Basically this command:
`msgmerge --update --backup=off id_ID.po custom-osd@neuromorph.pot`
Let me know if you face any issues.

Thanks again and sorry for the inconvenience. The extension is expected to be stable now with mainly just maintenance/ bug fix.

**Comment by neuromorph** [comment]
@IlhamSetiawan  tagging you in case notification is missed. Please comment if you will be working further on it (as per my previous comment) whenever you get free time.

**Comment by Nosis** [comment]
Hello, I made the translation into Spanish

**Comment by neuromorph** [comment]
Hello @Nosis ,
Thanks a lot for the translation! 
Please raise a separate pull request with your Spanish translation. 
Looking forward!

**Pull request merged**
